### ISSUE TITLE
Passing an array from Parse into stringify yields different output

### ISSUE THREAD

**Issue by kenperkins** [tj/node-querystring#72] opened 2013-08-01 16:52 UTC
``` javascript

var input = 'id=1&id=2';
qs.stringify(qs.parse(input));
```

output:

```
'id[0]=1&id[1]=2'
```

**Comment by tj** [comment] 2013-08-01 16:54
rad thanks, I'll try and look into this soon

**Comment by buschtoens** [comment] 2013-09-08 23:57
I personally find, that we shouldn't focus on returning the same output as the input (which is impossible anyways). We should focus one returning the shortest possible output.

Yeah, so basically this is a duplicate of #71.
Closing, if you don't mind. ;)

**Closed as completed by buschtoens** 2013-09-08 23:57 UTC
